remove repetitive lines in test file
the-cafe/git-ai-commit pull request #53
Opened 2024-08-13 03:56 UTC by Seif-Mamdouh

## Description

## Test Plan

2024-08-13 20:34 UTC, Seif-Mamdouh commented on ai_commit_msg/core/gen_commit_msg.py
>    return prefix + ai_gen_commit_msg
Another solution is we can also have both `truncation` and switching to a `bigger model`

Proposed solution
```
if str(select_model) in OPEN_AI_MODEL_LIST:
        try:
            return OpenAiService().chat_with_openai(prompt)
        except Exception as e:
            if "maximum context length" in str(e) or "Request too large" in str(e):
                Logger().log(f"Switching to gpt-4 due to token limit: {e}")
                try:
                    return OpenAiService().chat_with_openai(prompt, model="gpt-4")
                except Exception as e2:
                    if "maximum context length" in str(e2) or "Request too large" in str(e2):
                        return None
                    else:
                        raise e2
            else:
                raise e
    elif select_model.startswith("ollama"):
        return OLlamaService().chat_completion(prompt)
    elif select_model in ANTHROPIC_MODEL_LIST:
        return AnthropicService().chat_completion(prompt)

    return None

  ai_gen_commit_msg = try_generate_message(diff)


  if ai_gen_commit_msg is None:
    truncated_diff = truncate_diff(diff)
    ai_gen_commit_msg = try_generate_message(truncated_diff)


  if ai_gen_commit_msg is None:
    Logger().log(f"Unsupported or token limit exceeded for model: {select_model}")
```

2024-08-13 20:47 UTC, ming1in requested changes

2024-08-13 20:47 UTC, ming1in commented on ai_commit_msg/services/openai_service.py
> +    def chat_with_openai(self, messages, model=None):
we never use this `model` param, can we get rid of it. We should try to always use the model that's the user defines

2024-08-13 20:47 UTC, ming1in commented on ai_commit_msg/core/gen_commit_msg.py
> +                raise e
we should try to handle all of this in the `OpenAiService` itself, the user of the OpenAiService shouldn't have to think about open ai error handling

2024-08-13 20:47 UTC, ming1in commented on ai_commit_msg/core/gen_commit_msg.py
> +            if "maximum context length" in str(e) or "Request too large" in str(e):
Open ai returns error code in their API, we should check if these specific codes instead of the message itself. 

In this case we can to check for the `context_length_exceeded` code

2024-08-13 20:47 UTC, ming1in commented on ai_commit_msg/core/gen_commit_msg.py
> +            if "maximum context length" in str(e) or "Request too large" in str(e):
Check out this Open Ai docs on all their errors 

https://platform.openai.com/docs/guides/error-codes/python-library-error-types

We should do a review and make sure we're handling all of them properly

2024-08-13 20:47 UTC, ming1in commented on ai_commit_msg/core/gen_commit_msg.py
> +  def try_generate_message(current_diff):
why does this need to be a nested function? The `diff` string is globally accessible in the `generate_commit_message` function

2024-08-13 20:51 UTC, ming1in requested changes

2024-08-13 20:51 UTC, ming1in commented on ai_commit_msg/utils/diff_truncator.py
> +    truncated.extend(lines[-400:])
this code assumes that the `max_lines` is always 500. we should make this work with any value for `max_lines`

2024-08-13 20:51 UTC, ming1in commented on ai_commit_msg/core/gen_commit_msg.py
>    return prefix + ai_gen_commit_msg
we can recommend to the user to switch to a better model, but we shouldn't do it automatically. Users will be wary about LLM usage cost

2024-08-13 23:53 UTC, Seif-Mamdouh commented on ai_commit_msg/utils/diff_truncator.py
> +}
Ref link: https://platform.openai.com/docs/models

2024-08-14 03:13 UTC, ming1in commented on ai_commit_msg/services/openai_service.py
> +        truncated_messages.append({"role": "user", "content": truncated_diff})
the structure of this is a bit hard to read and brittle. Can we rename 

`truncated_messages` -> `system_message` and use a filter to get the system message

and pull out messages[-1]["content"] in a `user_message` variable

2024-08-14 03:17 UTC, ming1in commented on ai_commit_msg/utils/diff_truncator.py
> +}
is there a dynamic way to obtain the token limit?

2024-08-15 14:38 UTC, ming1in commented on ai_commit_msg/cli/hook_handler.py
> +            print("Please write your commit message manually.")
we should do the error handling inside `prepare_commit_msg_hook` since that has the core logic of generating the commit message and updating the `COMMIT_EDITMSG` file

2024-08-15 16:51 UTC, ming1in commented on ai_commit_msg/services/model_error_handling.py
> +        "BadRequestError": "EXCEEDED_TOKEN_SIZE",
lets create an enum for our application-level error codes

2024-08-15 16:56 UTC, ming1in requested changes

2024-08-15 16:56 UTC, ming1in commented on ai_commit_msg/prepare_commit_msg_hook.py
> +      GitService.update_commit_message(error_message)
wouldn't this just add the error as a commit message? We should also not add this banner if we run into an error. we should add a separate warning banner. Lets have separate functions in `GitService`, each responsible for returning different banners 

https://github.com/ming1in/ai-commit-msg/blob/1cfe51400d4b8d3be11ae901ead3bdd59c7a59ad/ai_commit_msg/services/git_service.py#L42-L51

2024-08-15 17:01 UTC, ming1in commented on ai_commit_msg/cli/gen_ai_commit_message_handler.py
> +        print("Please enter your commit message manually:")
we should use the logger instead of print here

2024-08-15 17:03 UTC, ming1in commented on ai_commit_msg/services/model_error_handling.py
> +def map_error(provider: str, error_code: str, original_error: Exception):
if we want to keep this logic, we should move this to `/utils`. This doesn't seem like it belongs in the `/service` directory

2024-08-15 23:26 UTC, ming1in requested changes

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/cli/gen_ai_commit_message_handler.py
> +from venv import logger
I dont think we need this

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/services/git_service.py
> -    new_content = commit_message + '\n\n' + header + '\n' + existing_content
we should keep the logic where we read the existing logic in here

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/prepare_commit_msg_hook.py
> +    filtered_content = "\n".join([line for line in existing_content.splitlines() if not line.strip().startswith('#')])
we shouldn't have to worry about the existing content in `COMMIT_EDITMSG` here

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/services/model_error_handling.py
> +}
can we also move all these values into the util function

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/utils/errorr_handling.py
> +
this files name has a typo `errorr_handling.py`

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/utils/errorr_handling.py
> +    return AIModelHandlerError(provider, error_type, original_error)
can we get rid of these extra print statements

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/services/git_service.py
> +# This commit message was generated by `ai-commit-msg`                                                                                  #
we should get ride the `This commit message was generated by `ai-commit-msg`` line in the error banner since we actually failed to complete it here

2024-08-15 23:26 UTC, ming1in commented on ai_commit_msg/services/anthropic_service.py
> +    return error_type
do we need a whole seperate function for this?

2024-08-16 00:21 UTC, ming1in requested changes

2024-08-16 00:21 UTC, ming1in commented on ai_commit_msg/prepare_commit_msg_hook.py
> +    success_banner = GitService.get_success_banner()
nit: we should get the success banner after we know we got a commit message in line 22

2024-08-16 00:21 UTC, ming1in commented on ai_commit_msg/services/model_error_handling.py
> +class AIModelHandlerError(Exception):
we should also move this to a `utils`

2024-08-16 00:21 UTC, ming1in commented on ai_commit_msg/services/model_error_handling.py
> +AI_MODEL_ERRORS = get_ai_model_errors()
what do we need this variable for?

2024-08-16 00:21 UTC, ming1in commented on ai_commit_msg/prepare_commit_msg_hook.py
> +        GitService.update_commit_message()
what other types of `Exception` can `generate_commit_message` throw besides `AIModelHandlerError`

2024-08-16 00:21 UTC, ming1in commented on ai_commit_msg/utils/get_ai_model_errors.py
> +def get_ai_model_errors():
can we just name this as a variable `AI_MODEL_ERRORS`. Why did we make this a function, it could be a variable if it returns a static value

2024-08-16 00:49 UTC, ming1in approved these changes

2024-08-16 00:51 UTC, merged